package sk.insomnia.rowingRace.remote;

public enum CSAFECommand {
	CSAFE_GETSTATUS_CMD(0x80,1,1),
	CSAFE_RESET_CMD(0x81,1,0),
	CSAFE_GOIDLE_CMD(0x82,1,0),
	CSAFE_GOHAVEID_CMD(0x83,1,0),
	CSAFE_GOINUSE_CMD(0x85,1,0),
	CSAFE_GOFINISHED_CMD(0x86,1,0),
	CSAFE_GOREADY_CMD(0x87,1,0),
	CSAFE_BADID_CMD(0x88,1,0),
	CSAFE_GETVERSION_CMD(0x91,1,7),
	CSAFE_GETID_CMD(0x92,1,5),
	CSAFE_GETUNITS_CMD(0x93,1,1),
	CSAFE_GETSERIAL_CMD(0x94,1,9),	
	CSAFE_GETODOMETER_CMD(0x9B,1,5),
	CSAFE_GETERRORCODE_CMD(0x9C,1,3),
	CSAFE_GETTWORK_CMD(0xA0,1,3),
	CSAFE_GETHORIZONTAL_CMD(0xA1,1,3),
	CSAFE_GETCALORIES_CMD(0xA3,1,2),
	CSAFE_GETPROGRAM_CMD(0xA4,1,1),
	CSAFE_GETPACE_CMD(0xA6,1,3),
	CSAFE_GETCADENCE_CMD(0xA7,1,3),
	CSAFE_GETUSERINFO_CMD(0xAB,1,5),
	CSAFE_GETHRCUR_CMD(0xB0,1,1),
	CSAFE_GETPOWER_CMD(0xB4,1,3),
	CSAFE_AUTOUPLOAD_CMD(0x01,1,0),
	CSAFE_IDDIGITS_CMD(0x10,1,0),
	CSAFE_SETDATE_CMD(0x12,3,0),
	CSAFE_SETTIMEOUT_CMD(0x13,1,0),
	CSAFE_SETUSERCFG1_CMD(0x1A,-1,-1),
	CSAFE_SETTWORK_CMD(0x20,3,0),
	CSAFE_SETHORIZONTAL_CMD(0x21,3,0),
	CSAFE_SETCALORIES_CMD(0x23,2,0),
	CSAFE_SETPROGRAM_CMD(0x24,2,0),
	CSAFE_SETPOWER_CMD(0x34,2,0),
	CSAFE_GETCAPS_CMD(0x70,1,11),
	CSAFE_SETPMCFG_CMD(0x76,-1,-1),
	CSAFE_SETPMDATA_CMD(0x77,-1,-1),
	CSAFE_GETPMCFG_CMD(0x7E,-1,-1),
	CSAFE_GETPMDATA_CMD(0x7F,-1,-1),
	CSAFE_GETWORKOUT_STATE(0x8D,1,1),
	CSAFE_GET_RACEMODESTATUS(0x98,1,15),
	CSAFE_PM_GET_WORKTIME(0xA0,1,4),
	CSAFE_PM_GET_PROJECTED_WORKTIME(0xA1,1,4),
	CSAFE_PM_GET_TOTAL_RESTTIME(0xA2,1,4),
	CSAFE_PM_GET_WORKDISTANCE(0xA3,1,4),
	CSAFE_PM_GET_TOTAL_WORKDISTANCE(0xA4,1,4),
	CSAFE_PM_GET_PROJECTED_WORKDISTANCE(0xA5,1,4),
	CSAFE_PM_GET_RESTDISTANCE(0xA6,1,2),
	CSAFE_PM_GET_TOTAL_RESTDISTANCE(0xA7,1,4),
	CSAFE_PM_GET_STROKE_500M_PACE(0xA8,1,4),
	CSAFE_PM_GET_STROKE_POWER(0xA9,1,4),
	CSAFE_PM_GET_STROKE_CALORICBURNRATE(0xAA,1,4),
	CSAFE_PM_GET_SPLIT_AVG_500M_PACE(0xAB,1,4),
	CSAFE_PM_SET_SCREENSTATE(0x13,2,0),
	CSAFE_PM_CONFIGURE_WORKOUT(0x14,1,0),
	CSAFE_PM_SET_WORKOUTTYPE(0x01,1,0),
	CSAFE_PM_SET_STARTTYPE(0x02,1,0),
	CSAFE_PM_SET_WORKOUTDURATION(0x03,5,0),
	CSAFE_PM_SET_RESTDURATION(0x04,2,0),
	CSAFE_PM_SET_SPLITDURATION(0x05,5,0),
	CSAFE_PM_SET_TARGETPACETIME(0x06,4,1),
	CSAFE_PM_SET_RACEOPERATIONTYPE(0x1E,4,0),
	CSAFE_PM_GET_WORKOUTSTATE(0x8D,1,1);
	
	
	private int commandIdentifier;
	private int requestBytesNumber;
	private int responseBytesNumber;
	
	CSAFECommand(int commandIdentifier,int requestBytesNumber, int responseBytesNumber){
		this.commandIdentifier = commandIdentifier;
		this.requestBytesNumber = requestBytesNumber;
		this.responseBytesNumber = responseBytesNumber;
	}
	public int getCommandIdentifier() {
		return commandIdentifier;
	}
	public int getRequestBytesNumber() {
		return requestBytesNumber;
	}
	public int getResponseBytesNumber() {
		return responseBytesNumber;
	}
	
	
}
